import { useState, type FormEvent } from 'react'
import { Navigate } from 'react-router-dom'
import { supabase, setRememberMe, supabaseConfigError } from '@/lib/supabase'
import { useAuth } from '@/context/AuthContext'
import { homePathForRole } from '@/lib/utils'
import { ThemeToggle } from '@/components/ThemeToggle'
import { Modal } from '@/components/ui/Modal'
import logoUrl from '@/assets/maktab_logo_transparent.png'

const FEATURES = ['إدارة الطلبة والملفات المدرسية', 'رصد الحضور والغياب بذكاء', 'متابعة العلامات والنتائج', 'الجداول والخطط الدراسية والتقارير']

export function Login() {
  const { session, profile, loading } = useAuth()
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false); const [showPassword, setShowPassword] = useState(false); const [remember, setRemember] = useState(true); const [caps, setCaps] = useState(false)
  const [forgot, setForgot] = useState(false); const [forgotEmail, setForgotEmail] = useState(''); const [forgotSent, setForgotSent] = useState(false); const [forgotError, setForgotError] = useState<string | null>(null); const [forgotLoading, setForgotLoading] = useState(false)
  if (!loading && session && profile) return <Navigate to={profile.must_reset_password ? '/reset-password' : homePathForRole(profile.role)} replace />
  async function submit(e: FormEvent) { e.preventDefault(); if (supabaseConfigError) return setError(supabaseConfigError); setError(null); setSubmitting(true); setRememberMe(remember); const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); setSubmitting(false); if (authError) setError('البريد الإلكتروني أو كلمة المرور غير صحيحة.') }
  async function sendReset(e: FormEvent) { e.preventDefault(); if (!forgotEmail.trim()) return setForgotError('أدخل بريدك الإلكتروني أولاً.'); setForgotLoading(true); const { error: resetError } = await supabase.auth.resetPasswordForEmail(forgotEmail.trim(), { redirectTo: `${window.location.origin}/reset-password` }); setForgotLoading(false); if (resetError) return setForgotError(resetError.message); setForgotSent(true) }
  return <main dir="rtl" lang="ar" className="relative flex min-h-dvh overflow-hidden bg-[#fbfaf7] text-[#242321]">
    <div className="absolute left-5 top-5 z-20"><ThemeToggle /></div>
    <section className="relative hidden w-[46%] flex-col justify-between overflow-hidden bg-[#242321] px-12 py-12 text-[#fbfaf7] lg:flex">
      <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'linear-gradient(135deg, transparent 0 48%, #d8c29a 49% 50%, transparent 51%)', backgroundSize: '52px 52px' }} />
      <div className="relative flex items-center gap-4"><img src={logoUrl} alt="شعار مدرسة الملك حسين بن طلال" className="size-16 object-contain" /><div><p className="text-xs tracking-[0.25em] text-[#d8c29a]">البوابة الرقمية</p><p className="mt-1 text-lg font-bold">مدرسة الملك حسين بن طلال</p><p className="text-sm text-[#c7c3b9]">الثانوية الشاملة للبنين</p></div></div>
      <div className="relative max-w-lg"><p className="mb-4 text-sm font-semibold text-[#d8c29a]">نحو مدرسة أكثر اتصالاً</p><h1 className="text-5xl font-black leading-[1.25] tracking-tight">كل ما تحتاجه المدرسة، في مساحة واحدة.</h1><p className="mt-6 max-w-md text-base leading-8 text-[#c7c3b9]">من الحضور والغياب إلى العلامات والجداول، إدارة مدرسية حديثة مصممة لتبسط يومكم.</p><ul className="mt-8 grid gap-3">{FEATURES.map((feature) => <li key={feature} className="flex items-center gap-3 text-sm text-[#e8e3d8]"><span className="size-2 rounded-full bg-[#d8c29a]" />{feature}</li>)}</ul></div>
      <p className="relative text-xs text-[#918c82]">© {new Date().getFullYear()} مدرسة الملك حسين بن طلال</p>
    </section>
    <section className="flex w-full items-center justify-center px-5 py-16 sm:px-10 lg:w-[54%] lg:px-20"><div className="w-full max-w-md">
      <div className="mb-10 lg:hidden"><img src={logoUrl} alt="شعار المدرسة" className="mb-5 size-16 object-contain" /><p className="text-sm font-bold text-[#b18a4b]">مدرسة الملك حسين بن طلال</p><h1 className="mt-1 text-2xl font-black">الثانوية الشاملة للبنين</h1></div>
      <div className="mb-9"><p className="mb-3 text-sm font-semibold text-[#b18a4b]">تسجيل الدخول الآمن</p><h2 className="text-4xl font-black tracking-tight">مرحباً بعودتك</h2><p className="mt-3 text-sm leading-7 text-[#77736b]">أدخل بياناتك للوصول إلى لوحة المدرسة.</p></div>
      {supabaseConfigError && <div role="alert" className="mb-5 rounded-xl border border-[#d8c29a] bg-[#f5efe3] p-4 text-sm leading-6">{supabaseConfigError}</div>}
      {error && <div role="alert" className="mb-5 rounded-xl border border-[#c9b6a8] bg-[#f6eee8] p-4 text-sm text-[#6c4436]">{error}</div>}
      <form onSubmit={submit} className="grid gap-5"><label className="grid gap-2 text-sm font-semibold">البريد الإلكتروني<input id="email" type="email" required autoFocus autoComplete="username" placeholder="name@school.edu.jo" value={email} onChange={e => setEmail(e.target.value)} className="h-14 rounded-xl border border-[#dedbd3] bg-white px-4 outline-none transition focus:border-[#b18a4b] focus:ring-4 focus:ring-[#d8c29a]/20" /></label><label className="grid gap-2 text-sm font-semibold">كلمة المرور<div className="relative"><input id="password" type={showPassword ? 'text' : 'password'} required autoComplete="current-password" placeholder="أدخل كلمة المرور" value={password} onChange={e => setPassword(e.target.value)} onKeyUp={e => setCaps(e.getModifierState('CapsLock'))} onKeyDown={e => setCaps(e.getModifierState('CapsLock'))} className="h-14 w-full rounded-xl border border-[#dedbd3] bg-white px-4 pl-14 outline-none transition focus:border-[#b18a4b] focus:ring-4 focus:ring-[#d8c29a]/20" /><button type="button" onClick={() => setShowPassword(v => !v)} aria-label={showPassword ? 'إخفاء كلمة المرور' : 'إظهار كلمة المرور'} className="absolute left-4 top-1/2 -translate-y-1/2 text-xs font-bold text-[#b18a4b]">{showPassword ? 'إخفاء' : 'إظهار'}</button></div>{caps && <span className="text-xs text-[#8c6e35]">مفتاح الأحرف الكبيرة مفعّل</span>}</label><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2 text-[#77736b]"><input type="checkbox" checked={remember} onChange={e => setRemember(e.target.checked)} className="size-4 accent-[#b18a4b]" />تذكرني</label><button type="button" onClick={() => { setForgotEmail(email); setForgotError(null); setForgotSent(false); setForgot(true) }} className="font-bold text-[#b18a4b]">نسيت كلمة المرور؟</button></div><button disabled={submitting} className="mt-2 h-14 rounded-xl bg-[#242321] text-sm font-bold text-white transition hover:bg-[#3b3935] disabled:opacity-50">{submitting ? 'جارٍ التحقق...' : 'دخول إلى النظام'}</button></form>
      <p className="mt-8 text-center text-xs text-[#9a958b]">نظام إدارة مدرسي آمن وموثوق</p>
    </div></section>
    {forgot && <Modal title="استعادة كلمة المرور" onClose={() => setForgot(false)}>{forgotSent ? <div className="grid gap-4 text-sm leading-7"><p>إذا كان البريد مرتبطاً بحساب، فسيصلك رابط لاستعادة كلمة المرور.</p><button onClick={() => setForgot(false)} className="rounded-lg bg-[#242321] px-4 py-3 font-bold text-white">إغلاق</button></div> : <form onSubmit={sendReset} className="grid gap-4"><p className="text-sm leading-7 text-[#77736b]">أدخل بريدك الإلكتروني وسنرسل لك رابطاً آمناً.</p><input type="email" required value={forgotEmail} onChange={e => setForgotEmail(e.target.value)} className="h-12 rounded-lg border border-[#dedbd3] px-3" />{forgotError && <p className="text-sm text-[#6c4436]">{forgotError}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={() => setForgot(false)} className="rounded-lg border px-4 py-2">إلغاء</button><button disabled={forgotLoading} className="rounded-lg bg-[#242321] px-4 py-2 font-bold text-white">{forgotLoading ? 'جارٍ الإرسال...' : 'إرسال الرابط'}</button></div></form>}</Modal>}
  </main>
}
